project:
  type: website

website:
  title: "toggle"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/toggle/
  repo-actions: [edit, issue]
  sidebar:
    logo: "toggle-animated-logo.svg"
    logo-alt: "A hexagon logo for the toggle Quarto extension."
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/toggle/
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Examples"
        contents:
        - text: "Toggle for All Cells"
          href: qtoggle-all-cells-example.qmd
        - text: "Toggle Specific Cells"
          href: qtoggle-specific-cells-example.qmd
      - section: "Support"
        contents:
        - text: "FAQ"
          href: qtoggle-faq.qmd
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/toggle/issues/new/choose
      - section: "Extra"
        contents:
        - qtoggle-release-notes.qmd

format: 
  html:
    toc: true
